### ISSUE TITLE
Can't find implementation for structural reparameterization trick proposed in the paper

### ISSUE THREAD

**Issue by ScottHoang** [ZJCV/ZCls#1]
Hi,
I'm interested in your structural reparameterization implementation but cannot find it in your repo. Did I miss it? Can you help?
Thanks!

**Comment by zjykzj** [comment]
> Hi,
> I'm interested in your structural reparameterization implementation but cannot find it in your repo. Did I miss it? Can you help?
> Thanks!

Hi, @ScottHoang . About repVGG, the key file is 

```
zcls/model/layers/repvgg_block.py
zcls/model/layers/repvgg_util.py
```

## how to use it?

you can look at `zcls/model/conv_help.py`, there are two func:

```
insert_repvgg_block
fuse_repvgg_block
```

## how to test it ?

```
tests/test_model/test_layer/test_repvgg_block.py
tests/test_model/test_recognizer/test_repvgg.py
```

**Comment by ScottHoang** [comment]
thank you!
