### ISSUE TITLE
Your network is  very great.I want to regard  it as backbone.Need to load pre-training parameters？

### ISSUE THREAD

**Issue by cwl-amour** [ZJCV/ZCls#4]
Your network is  very great.I want to regard  it as backbone.Need to load pre-training parameters？ 
For Example？I use ResNet，load resnet50-19c8e357.pth
Can you help?Thanks！

**Comment by zjykzj** [comment]
> Your network is very great.I want to regard it as backbone.Need to load pre-training parameters？
> For Example？I use ResNet，load resnet50-19c8e357.pth
> Can you help?Thanks！

hi @cwl-amour , you can check the online documentation, where you can find out how to load the pre-training model. At the same time, zcls also provides some pretraining models
